/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32xxxx.h"
#include "stm32f4xx_hal_rcc.h"
#include "stm32f4xx_hal_port.h"
#include "stm32f4xx_hal_spi.h"
#include "stm32f4xx_app_irq.h"
#include "app_gpio.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t DET_ErrorCode[50]; /* ErrCode */
uint8_t DET_ServiceId[50]; /* Sid */
uint8_t DET_ModuleId[50]; /* Mid */

int main(void)
{
  /* Led Setup */
  nvic_irq_init();
  led_port_init();
  push_button_port_init();

	while(1)
  {
//	    toggle_led();
//	    for(int i = 0; i<5000000; i++);
    /* LED Toggle */
  }
}
